{% set name = "ai4ts" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e49b2f2fc615c2d47fd345d8cddf484e26e6108d139ebe3a923abd83311167cc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation 
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - requests
    - numpy

test:
  requires:
    - python {{ python_min }}
  imports:
    - ai4ts

about:
  home: https://github.com/WenjieDu/AI4TS
  summary: |
    The client for Time-Series AI (https://time-series.ai), 
    where we build artificial intelligence for unified time-series analysis
  description: |
    The client for Time-Series AI (https://time-series.ai), 
    where we build artificial intelligence for unified time-series analysis.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://docs.pypots.com
  dev_url: https://github.com/WenjieDu/AI4TS

extra:
  recipe-maintainers:
    - WenjieDu
